.Dd $Mdocdate$
.Dt RIGG 1
.Os
.Sh NAME
.Nm rigg
.Nd run indie games
.Sh SYNOPSIS
.Nm rigg
.Op Fl v
.Ar engine
.Ar file
.Op Ar arguments
.Sh DESCRIPTION
.Nm
serves as an OpenBSD-adapted runtime for indie games based on certain engines
.Po
see
.Ar engine
.Pc .
There are many exceptions, mainly consisting of games using proprietary middleware.
.Pp
.Nm
handles availability of files by using
.Xr unveil 2
to hide bundled files that conflict with OpenBSD runtimes and libraries.
This is a common occurrence with commercial games based on open-source
frameworks like FNA, LibGDX, or HashLink.
Besides hiding the conflicting files,
.Nm
also enforces a restricted filesystem view of the minimum necessary for
the engine via
.Xr unveil 2 .
.Pp
The arguments are as follows:
.Bl -tag -width Ds
.It Ar engine
Specify the engine to use. Can select from:
.Ar mono ,
.Ar hl .
.It Ar file
The file to launch with the engine, e.g.
.Pa Game.exe
.Pq mono
or
.Pa hlboot.dat
.Pq hl .
.It Fl v
enable verbose output.
.El
.\" .Sh EXIT STATUS
.\" For sections 1, 6, and 8 only.
.Sh EXAMPLES
Run Mono game
.Pa Game.exe :
.Bd -literal -offset indent
$ rigg mono Game.exe
.Ed
.Pp
Run HashLink game
.Pa hlboot.dat
with
.Fl windowed
flag:
.Bd -literal -offset indent
$ rigg hl hlboot.dat -windowed
.Ed
.Sh SEE ALSO
.Xr unveil 2 ,
.Xr mono 1
.\" .Sh HISTORY
.Sh AUTHORS
.An -nosplit
.An Thomas Frohwein Aq Mt thfr@openbsd.org
.\" .Sh CAVEATS
.\" .Sh BUGS
.\" .Sh SECURITY CONSIDERATIONS
.\" Not used in OpenBSD.
