.Dd $Mdocdate$
.Dt RIGG 1
.Os
.Sh NAME
.Nm rigg
.Nd run indie games
.Sh SYNOPSIS
.Nm rigg
.Op Fl hv
.Op Fl e Ar engine
.Op Fl g Ar game
.Op file
.Sh DESCRIPTION
.Nm
serves as an OpenBSD-adapted runtime for indie games based on certain engines
.Po
see
.Fl e
.Pc .
There are many exceptions, mainly of games with those engines using proprietary
middleware.
.\" .Sh FILES
.\" .Sh EXIT STATUS
.\" For sections 1, 6, and 8 only.
.\" .Sh EXAMPLES
.\" .Sh DIAGNOSTICS
.\" For sections 1, 4, 6, 7, 8, and 9 printf/stderr messages only.
.Sh SEE ALSO
.Xr unveil 2 ,
.Xr mono 1
.\" .Sh HISTORY
.\" .Sh AUTHORS
.\" .Sh CAVEATS
.\" .Sh BUGS
.\" .Sh SECURITY CONSIDERATIONS
.\" Not used in OpenBSD.
